#
# docker compose file for testing
#

version: '3'
services:

  # database
  postgrestest:
    image: postgres:latest
    ports:
      - 5555:5432 # don't conflict with local postgresql
    container_name: importer_postgrestest_1
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  # importer
  importertest:
    image: docker.pkg.github.com/weng-lab/annotated-object-importer/annotated-object-importer:v0.7.1
    volumes:
      - ./test-resources:/data
    depends_on:
      - postgrestest
    container_name: importer_importertest_1
    command: tail -f /dev/null
